import Foundation

enum PresetThemes {
    static let all: [ThemeDefinition] = [paper, sepia, night, midnight, ocean, rose, parchment]

    static let paper = ThemeDefinition(
        id: "preset-paper",
        name: "Paper",
        isBuiltIn: true,
        backgroundType: .solid,
        bgColor: "FBF5EC",
        backgroundImageName: nil,
        backgroundDimOpacity: 0.5,
        ink: "382C26",
        ink2: "65584F",
        ink3: "8C7F75",
        accent: "BA5E38",
        accent2: "B87F33",
        accentSoft: "FEE8DB",
        onAccent: "FEFAF3",
        surface: "FFFCF7",
        surface2: "F5EEE4",
        line: "E1DACF",
        sage: "588E6F",
        uiFontFamily: "HankenGrotesk",
        titleFontFamily: "Newsreader",
        cardCornerRadius: 18,
        cardBorderStyle: .bordered,
        readerBgColor: nil,
        readerInkColor: nil,
        isDark: false
    )

    static let sepia = ThemeDefinition(
        id: "preset-sepia",
        name: "Sepia",
        isBuiltIn: true,
        backgroundType: .solid,
        bgColor: "F3E1CA",
        backgroundImageName: nil,
        backgroundDimOpacity: 0.5,
        ink: "483429",
        ink2: "6D594C",
        ink3: "8C7768",
        accent: "B4552D",
        accent2: "B27423",
        accentSoft: "F5D1BC",
        onAccent: "FBF2E5",
        surface: "F9EAD7",
        surface2: "EED8C0",
        line: "DDC8B2",
        sage: "498362",
        uiFontFamily: "HankenGrotesk",
        titleFontFamily: "Newsreader",
        cardCornerRadius: 18,
        cardBorderStyle: .bordered,
        readerBgColor: nil,
        readerInkColor: nil,
        isDark: false
    )

    static let night = ThemeDefinition(
        id: "preset-night",
        name: "Night",
        isBuiltIn: true,
        backgroundType: .solid,
        bgColor: "1C1611",
        backgroundImageName: nil,
        backgroundDimOpacity: 0.5,
        ink: "E6E1D7",
        ink2: "B2A9A0",
        ink3: "8E847B",
        accent: "D77E52",
        accent2: "D29C55",
        accentSoft: "442C21",
        onAccent: "FBF6EE",
        surface: "28211C",
        surface2: "342C27",
        line: "3E3631",
        sage: "73AE8B",
        uiFontFamily: "HankenGrotesk",
        titleFontFamily: "Newsreader",
        cardCornerRadius: 18,
        cardBorderStyle: .bordered,
        readerBgColor: nil,
        readerInkColor: nil,
        isDark: true
    )

    static let midnight = ThemeDefinition(
        id: "preset-midnight",
        name: "Midnight",
        isBuiltIn: true,
        backgroundType: .solid,
        bgColor: "0D1321",
        backgroundImageName: nil,
        backgroundDimOpacity: 0.5,
        ink: "D4DCE8",
        ink2: "9AA5B8",
        ink3: "6B7A90",
        accent: "5E8ACF",
        accent2: "7BA3D6",
        accentSoft: "1A2744",
        onAccent: "E8EDF5",
        surface: "141E33",
        surface2: "1C2940",
        line: "263352",
        sage: "5CA882",
        uiFontFamily: "HankenGrotesk",
        titleFontFamily: "Newsreader",
        cardCornerRadius: 18,
        cardBorderStyle: .bordered,
        readerBgColor: nil,
        readerInkColor: nil,
        isDark: true
    )

    static let ocean = ThemeDefinition(
        id: "preset-ocean",
        name: "Ocean",
        isBuiltIn: true,
        backgroundType: .solid,
        bgColor: "E8EEF2",
        backgroundImageName: nil,
        backgroundDimOpacity: 0.5,
        ink: "1E2D3D",
        ink2: "45596E",
        ink3: "6D8199",
        accent: "2E7D9B",
        accent2: "4A8FA8",
        accentSoft: "C8DDE8",
        onAccent: "F0F6FA",
        surface: "F0F5F8",
        surface2: "DCE5EB",
        line: "C4D1DA",
        sage: "4E9A7B",
        uiFontFamily: "HankenGrotesk",
        titleFontFamily: "Newsreader",
        cardCornerRadius: 18,
        cardBorderStyle: .bordered,
        readerBgColor: nil,
        readerInkColor: nil,
        isDark: false
    )

    static let rose = ThemeDefinition(
        id: "preset-rose",
        name: "Rose",
        isBuiltIn: true,
        backgroundType: .solid,
        bgColor: "F5E8EC",
        backgroundImageName: nil,
        backgroundDimOpacity: 0.5,
        ink: "3D1F2B",
        ink2: "6E4555",
        ink3: "997080",
        accent: "B45670",
        accent2: "C27A8E",
        accentSoft: "F0CED8",
        onAccent: "FBF0F3",
        surface: "FAF0F3",
        surface2: "EDDCE2",
        line: "E0C8D0",
        sage: "68A07E",
        uiFontFamily: "HankenGrotesk",
        titleFontFamily: "Newsreader",
        cardCornerRadius: 18,
        cardBorderStyle: .bordered,
        readerBgColor: nil,
        readerInkColor: nil,
        isDark: false
    )

    static let parchment = ThemeDefinition(
        id: "preset-parchment",
        name: "Parchment",
        isBuiltIn: true,
        backgroundType: .solid,
        bgColor: "F0E6D2",
        backgroundImageName: nil,
        backgroundDimOpacity: 0.5,
        ink: "3B2F1E",
        ink2: "5E4F3A",
        ink3: "877560",
        accent: "7B6B2D",
        accent2: "9A8742",
        accentSoft: "E8DCC0",
        onAccent: "F8F3E8",
        surface: "F7EEE0",
        surface2: "E6DAC5",
        line: "D4C5AA",
        sage: "6B8F4E",
        uiFontFamily: "HankenGrotesk",
        titleFontFamily: "Newsreader",
        cardCornerRadius: 18,
        cardBorderStyle: .bordered,
        readerBgColor: nil,
        readerInkColor: nil,
        isDark: false
    )
}
